# Generated by Django 3.0.6 on 2020-06-26 10:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_remove_newtestimonies_photo'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userProfile',
            new_name='publicUser',
        ),
    ]
