# Generated by Django 3.0.6 on 2020-06-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200626_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicuser',
            name='testimonies',
        ),
    ]
