# Generated by Django 3.0.8 on 2020-08-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200803_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='profile_img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
