# Generated by Django 3.0.6 on 2020-06-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_publicuser_testimonies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicuser',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='pending',
        ),
    ]
