# Generated by Django 3.0.6 on 2020-06-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200626_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicuser',
            name='city',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicuser',
            name='country',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicuser',
            name='gender',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicuser',
            name='username',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
