# Generated by Django 3.0.6 on 2020-06-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200628_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='totalRegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentNumber', models.PositiveIntegerField(verbose_name='Current Registered Number')),
            ],
            options={
                'verbose_name_plural': 'Total Registered User',
            },
        ),
    ]
