# Generated by Django 3.0.6 on 2020-07-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_totalregistereduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicuser',
            name='profile_img',
            field=models.ImageField(blank=True, max_length=20, null=True, upload_to='image'),
        ),
    ]
