# Generated by Django 3.0.6 on 2020-07-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_publicuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='static/images/avatar.png', max_length=20, null=True, upload_to='image'),
        ),
    ]
