# Generated by Django 3.0.6 on 2020-07-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200702_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='static/images/avatar.png', null=True, upload_to='images'),
        ),
    ]
