# Generated by Django 3.0.6 on 2020-07-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribemodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
