# Generated by Django 3.0.6 on 2020-07-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_subscribemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribemodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
