# Generated by Django 3.0.6 on 2020-06-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_post', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createPostModel',
        ),
    ]
