# Generated by Django 4.0.5 on 2023-03-26 20:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='askedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('answer', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Set Frequency Asked Question',
            },
        ),
        migrations.CreateModel(
            name='bibleQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.CharField(max_length=150)),
                ('quote', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Bible Quote Header',
            },
        ),
        migrations.CreateModel(
            name='newTestimonies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(editable=False, max_length=250)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='', editable=False)),
                ('category', models.CharField(choices=[('salvation', 'Salvation'), ('health', 'Health'), ('addiction', 'Addiction'), ('finance', 'Finance'), ('protection', 'Protection'), ('others', 'Others')], max_length=150)),
                ('body', tinymce.models.HTMLField()),
                ('author', models.CharField(max_length=250)),
                ('author_img', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonies',
            },
        ),
    ]
