# Generated by Django 3.0.6 on 2020-06-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newTestimonies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(default='', editable=False)),
                ('category', models.CharField(choices=[('salvation', 'Salvation'), ('health', 'Health'), ('addiction', 'Addiction'), ('finance', 'Finance'), ('protection', 'Protection'), ('others', 'Others')], max_length=150)),
                ('photo', models.ImageField(upload_to='images')),
                ('introduction', models.TextField(max_length=200)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonies',
            },
        ),
    ]
