# Generated by Django 3.0.8 on 2020-07-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtestimonies',
            name='setNameToAnonymous',
        ),
        migrations.AlterField(
            model_name='newtestimonies',
            name='category',
            field=models.CharField(choices=[('salvation', 'Salvation'), ('health', 'Health'), ('addiction', 'Addiction'), ('finance', 'Finance'), ('protection', 'Protection'), ('others', 'Others')], max_length=150),
        ),
    ]
