# Generated by Django 3.0.6 on 2020-06-26 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_publicuser_testimonies'),
        ('main_app', '0003_remove_newtestimonies_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtestimonies',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.publicUser', verbose_name=''),
        ),
    ]
