# Generated by Django 3.0.6 on 2020-06-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_newtestimonies_apporoved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newtestimonies',
            old_name='Apporoved',
            new_name='apporoved',
        ),
    ]
