# Generated by Django 3.0.6 on 2020-06-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200626_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newtestimonies',
            old_name='apporoved',
            new_name='approved',
        ),
    ]
