# Generated by Django 3.0.6 on 2020-06-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200626_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtestimonies',
            name='setNameToAnonymous',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
