# Generated by Django 3.0.6 on 2020-06-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200627_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtestimonies',
            name='user',
        ),
    ]
