# Generated by Django 3.0.6 on 2020-06-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_newtestimonies_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtestimonies',
            name='setNameToAnonymous',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
