# Generated by Django 3.0.6 on 2020-06-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200627_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtestimonies',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
