# Generated by Django 3.0.6 on 2020-06-27 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200626_1338'),
        ('main_app', '0015_auto_20200627_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtestimonies',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.publicUser', verbose_name=''),
            preserve_default=False,
        ),
    ]
