# Generated by Django 3.0.6 on 2020-06-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_newtestimonies_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtestimonies',
            name='user',
        ),
    ]
