# Generated by Django 3.0.6 on 2020-06-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_remove_newtestimonies_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtestimonies',
            name='unique_user',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
