# Generated by Django 3.0.6 on 2020-06-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_newtestimonies_unique_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newtestimonies',
            old_name='unique_user',
            new_name='userId',
        ),
    ]
