# Generated by Django 3.0.6 on 2020-07-01 14:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20200629_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtestimonies',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
