# Generated by Django 3.0.6 on 2020-07-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20200701_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtestimonies',
            name='author_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
