# Generated by Django 3.0.6 on 2020-07-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_newtestimonies_author_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtestimonies',
            name='author_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
