# Generated by Django 3.0.6 on 2020-07-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20200702_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtestimonies',
            name='author_img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
