# Generated by Django 3.0.6 on 2020-07-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20200702_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtestimonies',
            name='author_img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
