# Generated by Django 3.0.6 on 2020-07-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_auto_20200702_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtestimonies',
            name='test',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
