# Generated by Django 3.0.6 on 2020-07-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_newtestimonies_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtestimonies',
            name='test',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
