# Generated by Django 3.0.6 on 2020-07-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_auto_20200704_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtestimonies',
            name='test',
        ),
        migrations.AddField(
            model_name='newtestimonies',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newtestimonies',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
