# Generated by Django 3.0.6 on 2020-07-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_auto_20200705_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtestimonies',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newtestimonies',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newtestimonies',
            name='userId',
            field=models.CharField(editable=False, max_length=250),
        ),
    ]
