# Generated by Django 3.0.6 on 2020-07-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_auto_20200705_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='askedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Set Frequency Asked Question',
            },
        ),
    ]
