# Generated by Django 3.0.6 on 2020-07-06 17:03

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_askedquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='bibleQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Bible Quote Header',
            },
        ),
        migrations.AlterField(
            model_name='askedquestion',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
    ]
